# Generated by Django 4.2.7 on 2023-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='FechaFin',
            new_name='fechaFin',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='FechaInicio',
            new_name='fechaInicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='Total',
            new_name='total',
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
