# Generated by Django 4.2.7 on 2023-12-05 15:59

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_nationalidad_cliente_nacionalidad'),
        ('reservas', '0002_rename_fecha_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
