# Generated by Django 4.2.7 on 2023-12-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
