# Generated by Django 4.2.7 on 2023-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nationalidad',
            new_name='nacionalidad',
        ),
    ]
