# Generated by Django 4.2.7 on 2023-12-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipocabañas', '0001_initial'),
        ('comodidades', '0001_initial'),
        ('cabañas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabaña',
            name='comodidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comodidades.comodidad'),
        ),
        migrations.AddField(
            model_name='cabaña',
            name='tipocabaña',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tipocabañas.tipocabaña'),
        ),
    ]
